name: msm-Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Image Build
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        device:
          - beryllium-tianma
          - beryllium-ebbg

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install required packages
        run: |
          sudo dpkg --add-architecture i386
          sudo install -d -m 0755 /etc/apt/keyrings
          sudo wget -O /etc/apt/keyrings/winehq-archive.key \
            https://dl.winehq.org/wine-builds/winehq.key
          sudo chmod 644 /etc/apt/keyrings/winehq-archive.key
          sudo wget -O /etc/apt/sources.list.d/winehq-noble.sources \
            https://dl.winehq.org/wine-builds/ubuntu/dists/noble/winehq-noble.sources
          sudo apt-get update
          sudo apt-get install --install-recommends winehq-stable libsdl2-2.0-0 libsdl2-dev  build-essential uuid-dev clang llvm iasl nasm gcc-aarch64-linux-gnu abootimg python3-pil python3-git gettext libgcc-s1:i386 libstdc++6:i386  -y

      - name: Build an image for ${{ matrix.device }}
        run: |
          ./build.sh --device ${{ matrix.device }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.device }}
          path: ./*.img
